### ISSUE TITLE
Compiled release?

### ISSUE THREAD

**Issue by Keith94** [ohadts/FixedResolutionApp#1]
This app looks interesting, potentially useful for games. Is there a way you can provide the compiled binary to download and use it?

**Comment by ohadts** [comment]
Added to repo, "Fixed Resolution App.rar"
https://github.com/ohadts/FixedResolutionApp/blob/master/Fixed%20Resolution%20App.rar

**Comment by Keith94** [comment]
Thanks! Would you mind adding it to [releases page](https://github.com/ohadts/FixedResolutionApp/releases)? It's generally the most common and easy place to find it.

Has this app been tested a lot, and is it generally safe to use as well?

**Comment by ohadts** [comment]
I've added it to the releases page. This is the forum thread that make me
write it:
http://www.sevenforums.com/customization/89953-kvm-switch-windows-7-changing-screen-resolution.html
You can learn more about it there.

I Really don't know how the app will react in games, the idea is to stay
with same resolution if your EDID reading is for some reason broken (like a
cheap and crappy KVM).

**Comment by Keith94** [comment]
I see! Thanks for the information.
